apiVersion: v1
kind: Service
metadata:
  name: actions-to-eks-sample-service
  namespace: default
  labels:
    app: actions-to-eks-sample-app
spec:
  selector:
    app: actions-to-eks-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP