name: CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-release:
    name: Pre-Release
    uses: ./.github/workflows/build-and-push.yaml

  deploy:
    name: Deploy
    needs: pre-release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        environment: [Dev]
        region: [eu-west-1]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Download Deployment Artifacts
        uses: actions/download-artifact@v3
        with:
          name: deployment-artifacts

      - name: Substitute Values In Deployment Files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["cloud/deployment.yaml"]'
        env:
          COMMIT: ${{ needs.pre-release.outputs.commit }}

      - name: Configure Kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.6'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Update KubeConfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }} --region=${{ matrix.region }}
          
      - name: Deploy To Cluster
        shell: bash
        run: kubectl apply -n default -f cloud/
